name: CI

on:
  push:
    branches: [master]
  pull_request:     
    branches: [master]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v2

    - name: Build
      run: |
        cd task5/
        mkdir 3rdparty
        cd 3rdparty
        git clone https://github.com/google/googletest.git
        cd ..
        mkdir build
        cd build
        export GOOGLE_TEST_DIR=googletest
        cmake -DCMAKE_INSTALL_PREFIX=/home/runner/work/TP-2021-Spring/task5/ ..
        make
        make install
    - name: Test
      uses: akhtyamovpavel/ActionGtestReport@v0.0.9
      with:
        exec-path: "bin/CTestExe"
        report-path: "report.xml"
        working-directory: "task5/"

    - name: UploadArtifacts
      uses: actions/upload-artifact@v2
      with:
        name: Distributive
        path: /home/runner/work/TP-2021-Spring/TP-2021-Spring/task5/
